### ISSUE TITLE
not working on xiaomi phones

### ISSUE THREAD

**Issue by kunwar97** [PSD-Company/duo-navigation-drawer#8]
This navigation drawer is not working on some xiaomi phones.

**Comment by Alexander-1504** [comment]
I personally do not own a xiaomi phone so I haven't had the chance to test on those phones. Could you tell me what's going wrong?

**Comment by kunwar97** [comment]
The drawer is opening but the menu items are not getting selected. onClick is not working.

**Comment by mradzinski** [comment]
Just tested the demo app on several Xiaomi phones (Redmi Note 3, Redmi Note 3 Pro, Redmi 4A and Redmi Mix 2). It's working fine in all of them.

**Comment by amautone** [comment]
I have the same problem of @kunwar97, on devices running Android API 19 (KitKat, tested on a tablet and on a simulator with 4,6" screen size) . I have a custom "MenuFragment" with a RecyclerView inside, on Kitkat the RecyclerView is scrollable but items are not clickable while from Lollipop all is working fine

**Comment by mradzinski** [comment]
@amautone Are this devices sporting KitKat Xiaomi devices?

**Comment by amautone** [comment]
@mradzinski I just found that I was doing something _strange_ with the right margin of the RecyclerView inside the _ MenuFragment_. Now it is working properly (but anyway the behavior was strange because it was working on devices running Lollipop or above).

Ps: The device I was talking about in my last post was the Samsung Galaxy Note 8.0 (not the new one, the old tablet)
